### ISSUE TITLE
千帆大模型错误报告

### ISSUE THREAD

**Issue by xumingtian** [Ikaros-521/AI-Vtuber#1012]
### 操作系统

Windows

### Python 版本

不知道

### AI Vtuber 版本

不知道

### 描述问题

在点击一键运行后测试时出现错误：Traceback (most recent call last):
  File "C:\Users\Divinity\Desktop\AI-Vtuber-20240823\utils\gpt_model\my_wenxinworkshop.py", line 123, in get_resp
    resp_content = self.my_bot(
TypeError: 'NoneType' object is not callable

### 复现步骤

首先按照up文档中千帆大模型的教程填好了信息，接着运行，运行后输入文本返回语言都没有问题，但是1在ai该进行回答的时候报错：Traceback (most recent call last):
  File "C:\Users\Divinity\Desktop\AI-Vtuber-20240823\utils\gpt_model\my_wenxinworkshop.py", line 123, in get_resp
    resp_content = self.my_bot(
TypeError: 'NoneType' object is not callable

### 期望的结果

希望可以正常运行

### 截图或日志

![Uploading 微信图片_20241006200558.jpg…]()

**Comment by Ikaros-521** [comment]
图片看不到。NoneType就是实例化失败了，大概率是密钥错误导致实例化失败 或者 库版本低导致
