### ISSUE TITLE
🐛 Bug: edge tts播放完音頻後報錯

### ISSUE THREAD

**Issue by albertyu123456789** [Ikaros-521/AI-Vtuber#1060]
### 操作系统

Windows

### Python 版本

3.10.11

### AI Vtuber 版本

20241028整合包

### 描述问题

edge播放完來自text-generation-webui的文本後報錯

### 复现步骤

如問題所示

### 截图或日志

![螢幕擷取畫面 2024-11-17 000224](https://github.com/user-attachments/assets/33c41a95-9819-447c-92dd-526fbff554ed)

2024-11-17 00:00:58.411 | INFO     | utils.audio:data_priority_insert:617 - 待播放音频列表 优先级: 20 音频=D:\ai\AI-Vtuber-20241028\out\edge_tts_4.mp3
2024-11-17 00:01:05.633 | INFO     | __main__:callback:253 - 内部HTTP API callback接口 音频播放完成回调，待播放音频数量 ：1，待合成消息数量：0
INFO:     127.0.0.1:52315 - "POST /callback HTTP/1.1" 200 OK
2024-11-17 00:01:09.313 | ERROR    | utils.audio_handle.my_tts:edge_tts_api:352 - Traceback (most recent call last):
  File "D:\ai\AI-Vtuber-20241028\Miniconda3\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\ai\AI-Vtuber-20241028\Miniconda3\lib\asyncio\base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "D:\ai\AI-Vtuber-20241028\Miniconda3\lib\asyncio\base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "D:\ai\AI-Vtuber-20241028\Miniconda3\lib\asyncio\selector_events.py", line 501, in sock_connect
    return await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ai\AI-Vtuber-20241028\Miniconda3\lib\site-packages\aiohttp\client.py", line 562, in _request
    conn = await self._connector.connect(
  File "D:\ai\AI-Vtuber-20241028\Miniconda3\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\ai\AI-Vtuber-20241028\Miniconda3\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\ai\AI-Vtuber-20241028\Miniconda3\lib\site-packages\aiohttp\connector.py", line 1178, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "D:\ai\AI-Vtuber-20241028\Miniconda3\lib\site-packages\aiohttp\connector.py", line 979, in _wrap_create_connection
    async with ceil_timeout(timeout.sock_connect):
  File "D:\ai\AI-Vtuber-20241028\Miniconda3\lib\site-packages\async_timeout\__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "D:\ai\AI-Vtuber-20241028\Miniconda3\lib\site-packages\async_timeout\__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\ai\AI-Vtuber-20241028\utils\audio_handle\my_tts.py", line 348, in edge_tts_api
    await communicate.save(voice_tmp_path)
  File "D:\ai\AI-Vtuber-20241028\Miniconda3\lib\site-packages\edge_tts\communicate.py", line 523, in save
    async for message in self.stream():
  File "D:\ai\AI-Vtuber-20241028\Miniconda3\lib\site-packages\edge_tts\communicate.py", line 506, in stream
    async for message in self.__stream():
  File "D:\ai\AI-Vtuber-20241028\Miniconda3\lib\site-packages\edge_tts\communicate.py", line 365, in __stream
    async with aiohttp.ClientSession(
  File "D:\ai\AI-Vtuber-20241028\Miniconda3\lib\site-packages\aiohttp\client.py", line 1167, in __aenter__
    self._resp = await self._coro
  File "D:\ai\AI-Vtuber-20241028\Miniconda3\lib\site-packages\aiohttp\client.py", line 805, in _ws_connect
    resp = await self.request(
  File "D:\ai\AI-Vtuber-20241028\Miniconda3\lib\site-packages\aiohttp\client.py", line 566, in _request
    raise ServerTimeoutError(
aiohttp.client_exceptions.ServerTimeoutError: Connection timeout to host wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=6A5AA1D4EAFF4E9FB37E23D68491D6F4&ConnectionId=ca7904e0878d4b139b85a1e1f1fcf4a3

2024-11-17 00:01:09.316 | ERROR    | utils.audio_handle.my_tts:edge_tts_api:353 - Connection timeout to host wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=6A5AA1D4EAFF4E9FB37E23D68491D6F4&ConnectionId=ca7904e0878d4b139b85a1e1f1fcf4a3
2024-11-17 00:01:09.319 | ERROR    | utils.audio:my_play_voice:1302 - edge-tts合成失败，请排查服务端是否启动、是否正常，配置、网络等问题。如果排查后都没有问题，可能是接口改动导致的兼容性问题，可以前往官方仓库提交issue，传送门：https://github.com/Ikaros-521/AI-Vtuber/issues
2024-11-17 00:01:11.435 | INFO     | __main__:callback:253 - 内部HTTP API callback接口 音频播放完成回调，待播放音频数量 ：0，待合成消息数量：0
INFO:     127.0.0.1:52317 - "POST /callback HTTP/1.1" 200 OK

**Comment by albertyu123456789** [comment]
使用官方的text-generation-webui，以下為配置
![image](https://github.com/user-attachments/assets/afd84b76-3460-4470-8051-d9d1fd8c954f)
![image](https://github.com/user-attachments/assets/0c521f7f-2df0-45fe-9847-f5ae2ee50471)

**Comment by albertyu123456789** [comment]
![Screenshot_20241117_001318_ChatGPT.png](https://github.com/user-attachments/assets/7f7c03d4-d9cb-4d69-b76e-c1507403afac)

**Comment by Ikaros-521** [comment]
edge合成超时，得换库版本了，还是不建议用edge了 有限制

**Comment by albertyu123456789** [comment]
原來如此，有沒有推薦的替代

**Comment by Ikaros-521** [comment]
> 原來如此，有沒有推薦的替代

multitts 低占用 免费。
显卡好的话 可以用 gpt sovits等

**Comment by albertyu123456789** [comment]
> > 原來如此，有沒有推薦的替代
> 
> multitts 低占用 免费。
> 显卡好的话 可以用 gpt sovits等

好的，我會去試試看的
