### ISSUE TITLE
🐛 一些问题。。。 | [Bug] Some problem...

### ISSUE THREAD

**Issue by beilove** [Ikaros-521/AI-Vtuber#236]
#### 版本
v0.17.0

#### python版本&系统环境
python：3.10.11
系统：win10

#### 您做了什么操作？
聊天模式进行对话

#### 您遇到了什么问题？
在语音合成后无法输出声音
报错如下
2023-08-16 18:16:50,233 - E:\AI-Vtuber\utils\audio.py[line:451] - INFO: genshinvoice.top合成成功，输出到=./out/genshinvoice_top_92.wav
2023-08-16 18:16:50,263 - E:\AI-Vtuber\utils\common.py[line:318] - INFO: 内容已成功写入文件:log/字幕.txt
2023-08-16 18:16:50,885 - E:\AI-Vtuber\utils\audio.py[line:451] - INFO: genshinvoice.top合成成功，输出到=./out/genshinvoice_top_84.wav
2023-08-16 18:16:50,903 - E:\AI-Vtuber\utils\audio.py[line:594] - ERROR: Traceback (most recent call last):
  File "E:\AI-Vtuber\utils\audio.py", line 577, in only_play_audio
    voice_tmp_path = self.audio_speed_change(voice_tmp_path, random_speed)
  File "E:\AI-Vtuber\utils\audio.py", line 502, in audio_speed_change
    audio = AudioSegment.from_file(audio_path)
  File "E:\AI-Vtuber\Miniconda3\lib\site-packages\pydub\audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
  File "E:\AI-Vtuber\Miniconda3\lib\site-packages\pydub\utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "E:\AI-Vtuber\Miniconda3\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\AI-Vtuber\Miniconda3\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

#### 您期望的结果是怎样的？
这是环境配置的问题吗，我该如何解决这个（emmm

**Comment by Ikaros-521** [comment]
总记得有人有类似的问题，也一样的E盘，但就是获取不到文件。。。

**Comment by beilove** [comment]
谢谢你，我想应该没事了，我重新配置了一下ffmpeg就好了

**Comment by Ikaros-521** [comment]
可以的
