### ISSUE TITLE
星火api报错

### ISSUE THREAD

**Issue by langyaya** [Ikaros-521/AI-Vtuber#313]
配置选择：聊天模式——星火——api      appip和两个K也没问题

**Comment by langyaya** [comment]
不好意思是这个报错
2023-09-12 12:36:42,794 - D:\AI-Vtuber\utils\my_handle.py[line:870] - INFO: [主人]: 你好啊
Exception in thread Thread-11:
Traceback (most recent call last):
  File "D:\AI-Vtuber\Miniconda3\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "D:\AI-Vtuber\Miniconda3\lib\threading.py", line 1378, in run
    self.function(*self.args, **self.kwargs)
  File "D:\AI-Vtuber\utils\my_handle.py", line 1229, in process_last_data
    self.comment_handle(data)
  File "D:\AI-Vtuber\utils\my_handle.py", line 953, in comment_handle
    resp_content = self.llm_handle(self.chat_type, data_json)
  File "D:\AI-Vtuber\utils\my_handle.py", line 800, in llm_handle
    resp_content = self.sparkdesk.get_sparkdesk_resp(data["content"])
  File "D:\AI-Vtuber\utils\gpt_model\sparkdesk.py", line 55, in get_sparkdesk_resp
    return self.sparkAPI.chat(prompt)
  File "D:\AI-Vtuber\Miniconda3\lib\site-packages\sparkdesk_api\core.py", line 115, in chat
    ws = create_connection(url)
  File "D:\AI-Vtuber\Miniconda3\lib\site-packages\websocket\__init__.py", line 227, in create_connection
    websock.connect(url, **options)
  File "D:\AI-Vtuber\Miniconda3\lib\site-packages\websocket\__init__.py", line 523, in connect
    self.sock = ssl.wrap_socket(self.sock, **sslopt)
  File "D:\AI-Vtuber\Miniconda3\lib\ssl.py", line 1442, in wrap_socket
    return context.wrap_socket(
  File "D:\AI-Vtuber\Miniconda3\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\AI-Vtuber\Miniconda3\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "D:\AI-Vtuber\Miniconda3\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1007)

**Comment by Ikaros-521** [comment]
待ming修复bug
https://github.com/HildaM/sparkdesk-api

**Comment by HildaM** [comment]
下午弄，上午HR面😭



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年09月13日 00:30 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Ikaros-521/AI-Vtuber] 星火api报错 (Issue #313) |

Assigned #313 to @HildaM.

**Comment by Ikaros-521** [comment]
> 下午弄，上午HR面😭
> 
> 
> 
> ---- 回复的原邮件 ----
> | 发件人 | ***@***.***> |
> | 日期 | 2023年09月13日 00:30 |
> | 收件人 | ***@***.***> |
> | 抄送至 | ***@***.***>***@***.***> |
> | 主题 | Re: [Ikaros-521/AI-Vtuber] 星火api报错 (Issue #313) |
> 
> Assigned #313 to @HildaM.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were assigned.Message ID: ***@***.***>

工作要紧

**Comment by Ikaros-521** [comment]
重装解决 `websocket-client`  

`pip uninstall websocket-client`  

`pip install websocket-client`

**Comment by Ikaros-521** [comment]
升级星火库到1.5.0
https://github.com/HildaM/sparkdesk-api
