### ISSUE TITLE
文案语音合成失败

### ISSUE THREAD

**Issue by DoshideDK** [Ikaros-521/AI-Vtuber#349]
报错信息2023-10-09 18:46:01,361 - C:\AI-Vtuber\AI-Vtuber-20230924\talk.py[line:262] - INFO: 检测到单击键盘 s，即将停止录音~
2023-10-09 18:46:27,138 - C:\AI-Vtuber\AI-Vtuber-20230924\talk.py[line:262] - INFO: 检测到单击键盘 s，即将停止录音~
2023-10-09 18:46:30,636 - C:\AI-Vtuber\AI-Vtuber-20230924\main.py[line:3482] - INFO: 准备加载 文件：[test.txt]
2023-10-09 18:46:30,636 - C:\AI-Vtuber\AI-Vtuber-20230924\utils\common.py[line:339] - WARNING: 文件不存在，将创建新文件: test.txt
2023-10-09 18:46:30,636 - C:\AI-Vtuber\AI-Vtuber-20230924\main.py[line:3493] - INFO: 成功加载文案：test.txt
2023-10-09 18:46:31,902 - C:\AI-Vtuber\AI-Vtuber-20230924\main.py[line:3615] - INFO: 刷新文件列表
2023-10-09 18:46:45,321 - C:\AI-Vtuber\AI-Vtuber-20230924\main.py[line:3482] - INFO: 准备加载 文件：[吐槽.txt]
2023-10-09 18:46:45,322 - C:\AI-Vtuber\AI-Vtuber-20230924\utils\common.py[line:339] - WARNING: 文件不存在，将创建新文件: 吐槽.txt
2023-10-09 18:46:45,322 - C:\AI-Vtuber\AI-Vtuber-20230924\main.py[line:3493] - INFO: 成功加载文案：吐槽.txt
2023-10-09 18:46:46,400 - C:\AI-Vtuber\AI-Vtuber-20230924\main.py[line:3615] - INFO: 刷新文件列表
2023-10-09 18:47:00,008 - C:\AI-Vtuber\AI-Vtuber-20230924\main.py[line:3482] - INFO: 准备加载 文件：[data/copywriting/吐槽.txt]
2023-10-09 18:47:00,009 - C:\AI-Vtuber\AI-Vtuber-20230924\main.py[line:3493] - INFO: 成功加载文案：data/copywriting/吐槽.txt
2023-10-09 18:47:02,240 - C:\AI-Vtuber\AI-Vtuber-20230924\main.py[line:3615] - INFO: 刷新文件列表
2023-10-09 18:47:05,777 - C:\AI-Vtuber\AI-Vtuber-20230924\utils\audio.py[line:867] - INFO: 即将合成的文案：data/copywriting/吐槽.txt
2023-10-09 18:47:05,777 - C:\AI-Vtuber\AI-Vtuber-20230924\utils\audio.py[line:851] - ERROR: 没有找到要合并的音频文件
2023-10-09 18:47:05,777 - C:\AI-Vtuber\AI-Vtuber-20230924\utils\audio.py[line:1060] - INFO: 合成完毕后的音频位于 C:\AI-Vtuber\AI-Vtuber-20230924\out/吐槽.wav
2023-10-09 18:47:05,778 - C:\AI-Vtuber\AI-Vtuber-20230924\utils\audio.py[line:1063] - INFO: 移动音频到 C:\AI-Vtuber\AI-Vtuber-20230924\out/copywriting/
2023-10-09 18:47:05,779 - C:\AI-Vtuber\AI-Vtuber-20230924\utils\audio.py[line:1069] - ERROR: Traceback (most recent call last):
  File "C:\AI-Vtuber\AI-Vtuber-20230924\Miniconda3\lib\shutil.py", line 816, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'C:\\AI-Vtuber\\AI-Vtuber-20230924\\out/吐槽.wav' -> 'C:\\AI-Vtuber\\AI-Vtuber-20230924\\out/copywriting\\吐槽.wav'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\AI-Vtuber\AI-Vtuber-20230924\utils\audio.py", line 1064, in copywriting_synthesis_audio
    self.common.move_file(file_path, out_file_path)
  File "C:\AI-Vtuber\AI-Vtuber-20230924\utils\common.py", line 399, in move_file
    shutil.move(source_path, destination_path)
  File "C:\AI-Vtuber\AI-Vtuber-20230924\Miniconda3\lib\shutil.py", line 836, in move
    copy_function(src, real_dst)
  File "C:\AI-Vtuber\AI-Vtuber-20230924\Miniconda3\lib\shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\AI-Vtuber\AI-Vtuber-20230924\Miniconda3\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\AI-Vtuber\\AI-Vtuber-20230924\\out/吐槽.wav'

2023-10-09 18:47:05,780 - C:\AI-Vtuber\AI-Vtuber-20230924\main.py[line:3668] - ERROR: 合成失败！请排查原因

**Comment by Ikaros-521** [comment]
https://github.com/Ikaros-521/AI-Vtuber/commit/36ab43d12d46f6840f18df5174eace5770393608
