### ISSUE TITLE
🙋 pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`.

### ISSUE THREAD

**Issue by Ikaros-521** [Ikaros-521/AI-Vtuber#470]
## Question Report

- 搜索打开和关闭的 [GitHub 问题](https://github.com/eryajf/go-ldap-admin/issues)

请在提交问题之前回答这些问题，谢谢。 | Please answer these questions before submitting them. Thank you.

### 你使用了哪个版本？ | Which version did you use?
main

### 您使用的python版本&系统环境？ | Your usage python version & system?
python：3.10.11
系统：win11

### 实际行为 | Actual behavior
```
pygame 2.4.0 (SDL 2.26.4, Python 3.10.11)
Hello from the pygame community. https://www.pygame.org/contribute.html
D:\GitHub_pro\AI-Vtuber\venv\lib\site-packages\pydantic\_internal\_config.py:317: UserWarning: Valid config keys have changed in V2:
* 'underscore_attrs_are_private' has been removed
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "D:\GitHub_pro\AI-Vtuber\webui.py", line 14, in <module>
    from utils.audio import Audio
  File "D:\GitHub_pro\AI-Vtuber\utils\audio.py", line 16, in <module>
    from elevenlabs import generate, play, set_api_key
  File "D:\GitHub_pro\AI-Vtuber\venv\lib\site-packages\elevenlabs\__init__.py", line 1, in <module>
    from .api import *  # noqa F403
  File "D:\GitHub_pro\AI-Vtuber\venv\lib\site-packages\elevenlabs\api\__init__.py", line 2, in <module>
    from .history import *  # noqa F403
  File "D:\GitHub_pro\AI-Vtuber\venv\lib\site-packages\elevenlabs\api\history.py", line 9, in <module>
    from .voice import VoiceSettings
  File "D:\GitHub_pro\AI-Vtuber\venv\lib\site-packages\elevenlabs\api\voice.py", line 30, in <module>
    class VoiceClone(API):
  File "D:\GitHub_pro\AI-Vtuber\venv\lib\site-packages\elevenlabs\api\voice.py", line 38, in VoiceClone
    def computed_files_tuple(cls, values) -> List[str]:
  File "D:\GitHub_pro\AI-Vtuber\venv\lib\site-packages\pydantic\deprecated\class_validators.py", line 222, in root_validator
    return root_validator()(*__args)  # type: ignore
  File "D:\GitHub_pro\AI-Vtuber\venv\lib\site-packages\pydantic\deprecated\class_validators.py", line 228, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.4/u/root-validator-pre-skip
```

### 原因分析（如果可以） | Cause analysis (if possible)
pydantic版本问题

**Comment by Ikaros-521** [comment]
降低版本 `pip install pydantic==1.10.7`
