### ISSUE TITLE
🐛哔哩哔哩方案1 手机扫描 不能使用

### ISSUE THREAD

**Issue by Ikaros-521** [Ikaros-521/AI-Vtuber#498]
#### 您使用的版本？ | Your usage version?
例如：main

#### 您使用的python版本&系统环境？ | Your usage python version & system?
python：3.10.11
系统：win11

```
2023-12-07 20:48:17,307 - D:\GitHub_pro\AI-Vtuber\bilibili.py[line:422] - ERROR: Traceback (most recent call last):
  File "D:\GitHub_pro\AI-Vtuber\bilibili.py", line 406, in start_server
    credential = login.login_with_qrcode()
  File "D:\GitHub_pro\AI-Vtuber\venv\lib\site-packages\bilibili_api\login.py", line 116, in login_with_qrcode
    qrcode_data = update_qrcode_data()
  File "D:\GitHub_pro\AI-Vtuber\venv\lib\site-packages\bilibili_api\login.py", line 89, in update_qrcode_data
    qrcode_data = httpx.get(api["url"], follow_redirects=True).json()["data"]
  File "D:\GitHub_pro\AI-Vtuber\venv\lib\site-packages\httpx\_models.py", line 755, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "D:\GitHub_pro\AI-Vtuber\venv\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\GitHub_pro\AI-Vtuber\venv\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\GitHub_pro\AI-Vtuber\venv\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Ikaros-521** [comment]
被官方风控了,建议更换方案2
```Error: HTTP 412 - <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html lang="zh-cn">

<head>
    <meta http-equiv="Access-Control-Allow-Origin" content="*" />
    <meta http-equiv="Page-Enter" content="blendTrans(Duration=0.5)">
    <meta http-equiv="Page-Exit" content="blendTrans(Duration=0.5)">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta name="spm_prefix" content="333.937">
    <title>出错啦! - bilibili.com</title>
    <link rel="shortcut icon" href="//static.hdslb.com/images/favicon.ico">
    <script type="text/javascript" src="//s1.hdslb.com/bfs/static/jinkela/long/js/jquery/jquery1.7.2.min.js"></script>

</head>

<body>
    <div class="error-container">
        <div class="txt-item err-code">错误号:412</div>
        <div class="txt-item err-text">由于触发哔哩哔哩安全风控策略，该次访问请求被拒绝。</div>
        <div class="txt-item">The request was rejected because of the bilibili security control policy.</div>
        <div class="txt-item datetime_now"></div>
        <div class="txt-item user_url"></div>
        <div class="txt-item user_ip"></div>
        <div class="txt-item user_id"></div>
        <div class="check-input">
            <div class="title"></div>
            <div class="box-pic"></div>
            <div class="box"></div>
            <div class="state"></div>
        </div>
    </div>
    <script type="text/javascript" charset="utf-8" src="//security.bilibili.com/static/js/sha256.min.js"></script>
    <script type="text/javascript" charset="utf-8" src="//security.bilibili.com/static/js/js.cookie.min.js"></script>
    <script type="text/javascript" charset="utf-8" src="//security.bilibili.com/static/js/412.js"></script>
</body>
</html>
2023-12-07 23:20:46,150 - D:\GitHub_pro\AI-Vtuber\bilibili.py[line:422] - ERROR: Traceback (most recent call last):
  File "D:\GitHub_pro\AI-Vtuber\bilibili.py", line 406, in start_server
    credential = login.login_with_qrcode()
  File "D:\GitHub_pro\AI-Vtuber\venv\lib\site-packages\bilibili_api\login.py", line 129, in login_with_qrcode
    qrcode_data = update_qrcode_data()
  File "D:\GitHub_pro\AI-Vtuber\venv\lib\site-packages\bilibili_api\login.py", line 103, in update_qrcode_data
    return qrcode_data
UnboundLocalError: local variable 'qrcode_data' referenced before assignment
```

**Comment by Ikaros-521** [comment]
https://github.com/Ikaros-521/AI-Vtuber/issues/513
