### ISSUE TITLE
🙋 【SD报错】ERROR: unrecognized data stream contents when reading image file

### ISSUE THREAD

**Issue by Ikaros-521** [Ikaros-521/AI-Vtuber#566]
## Question Report

- 搜索打开和关闭的 [GitHub 问题](https://github.com/eryajf/go-ldap-admin/issues)

请在提交问题之前回答这些问题，谢谢。 | Please answer these questions before submitting them. Thank you.

### 你使用了哪个版本？ | Which version did you use?
main

### 您使用的python版本&系统环境？ | Your usage python version & system?
例如：
python：3.10.11
系统：win11

### 实际行为 | Actual behavior
```
2024-01-10 22:07:53 - E:\GitHub_pro\AI-Vtuber\utils\sd.py[line:123] - ERROR: unrecognized data stream contents when reading image file
Exception in thread Thread-4 (<lambda>):
Traceback (most recent call last):
  File "e:\GitHub_pro\AI-Vtuber\Miniconda3\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "e:\GitHub_pro\AI-Vtuber\Miniconda3\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "E:\GitHub_pro\AI-Vtuber\utils\sd.py", line 30, in <lambda>
    threading.Thread(target=lambda: asyncio.run(self.update_virtual_camera())).start()
  File "e:\GitHub_pro\AI-Vtuber\Miniconda3\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "e:\GitHub_pro\AI-Vtuber\Miniconda3\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "E:\GitHub_pro\AI-Vtuber\utils\sd.py", line 43, in update_virtual_camera
    resized_img = self.new_img.resize((cam.width, cam.height))
  File "e:\GitHub_pro\AI-Vtuber\Miniconda3\lib\site-packages\PIL\Image.py", line 2163, in resize
    self.load()
  File "e:\GitHub_pro\AI-Vtuber\Miniconda3\lib\site-packages\PIL\ImageFile.py", line 249, in load
    s = read(self.decodermaxblock)
  File "e:\GitHub_pro\AI-Vtuber\Miniconda3\lib\site-packages\PIL\PngImagePlugin.py", line 927, in load_read
    self.fp.read(4)  # CRC
AttributeError: 'NoneType' object has no attribute 'read'
```

**Comment by Ikaros-521** [comment]
SD确认加载了模型，然后在webui内随便画一个画激活一下就没问题了
