### ISSUE TITLE
🐛 一些问题。。。 | [Bug] Some problem...

### ISSUE THREAD

**Issue by yfqingmu** [Ikaros-521/AI-Vtuber#599]
win11系统，使用的整合包20240125的版本，保存配置后，点运行，出现以下错误，这个依赖是在哪个目录 安装 的，怎么自己补下。
pygame 2.5.0 (SDL 2.28.0, Python 3.10.11)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "D:\Program Files\AIVtuber\AI-Vtuber-20240125\bilibili2.py", line 26, in <module>
    from utils.my_handle import My_handle
  File "D:\Program Files\AIVtuber\AI-Vtuber-20240125\utils\my_handle.py", line 17, in <module>
    from .my_translate import My_Translate
  File "D:\Program Files\AIVtuber\AI-Vtuber-20240125\utils\my_translate.py", line 7, in <module>
    from pygtrans import Translate
ModuleNotFoundError: No module named 'pygtrans'

**Comment by yfqingmu** [comment]
ModuleNotFoundError: No module named 'pygtrans'
