### ISSUE TITLE
🐛 一些问题。。。 | [Bug] Some problem...

### ISSUE THREAD

**Issue by yfqingmu** [Ikaros-521/AI-Vtuber#602]
#### 您使用的版本？ | Your usage version?
整合包 20240125

#### 您使用的python版本&系统环境？ | Your usage python version & system?
系统：win11

#### 您使用的场景？ | Your usage scenarios?
点击一建运行，出现 错误
#### 您做了什么操作？ | What did you do?
点击一建运行
#### 您遇到了什么问题？ | What are your problems?
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "D:\Program Files\AIVtuber\AI-Vtuber-20240125\bilibili2.py", line 26, in <module>
    from utils.my_handle import My_handle
  File "D:\Program Files\AIVtuber\AI-Vtuber-20240125\utils\my_handle.py", line 17, in <module>
    from .my_translate import My_Translate
  File "D:\Program Files\AIVtuber\AI-Vtuber-20240125\utils\my_translate.py", line 7, in <module>
    from pygtrans import Translate
ModuleNotFoundError: No module named 'pygt

#### 您期望的结果是怎样的？ | What is your expected outcome?
正常运行，没有错误

**Comment by Ikaros-521** [comment]
安装缺失的依赖库
