### ISSUE TITLE
🙋 聊天页 谷歌语音识别失败，报错：ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接

### ISSUE THREAD

**Issue by Ikaros-521** [Ikaros-521/AI-Vtuber#620]
## Question Report

- 搜索打开和关闭的 [GitHub 问题](https://github.com/eryajf/go-ldap-admin/issues)

请在提交问题之前回答这些问题，谢谢。 | Please answer these questions before submitting them. Thank you.

### 你使用了哪个版本？ | Which version did you use?
main

### 您使用的python版本&系统环境？ | Your usage python version & system?
python：3.10.11
系统：win11

### 预期行为 | Expected behavior
聊天页，谷歌识别情况下，正常语音对话

### 实际行为 | Actual behavior
```
2024-02-04 23:05:21 - E:\GitHub_pro\AI-Vtuber\dy.py[line:389] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_pro\AI-Vtuber\dy.py", line 313, in do_listen_and_comment
    content = r.recognize_google(audio, language=config.get("talk", "google", "tgt_lang"))
  File "e:\GitHub_pro\AI-Vtuber\Miniconda3\lib\site-packages\speech_recognition\__init__.py", line 708, in recognize_google
    response = urlopen(request, timeout=self.operation_timeout)
  File "e:\GitHub_pro\AI-Vtuber\Miniconda3\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "e:\GitHub_pro\AI-Vtuber\Miniconda3\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "e:\GitHub_pro\AI-Vtuber\Miniconda3\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "e:\GitHub_pro\AI-Vtuber\Miniconda3\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "e:\GitHub_pro\AI-Vtuber\Miniconda3\lib\urllib\request.py", line 1377, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "e:\GitHub_pro\AI-Vtuber\Miniconda3\lib\urllib\request.py", line 1352, in do_open
    r = h.getresponse()
  File "e:\GitHub_pro\AI-Vtuber\Miniconda3\lib\http\client.py", line 1375, in getresponse
    response.begin()
  File "e:\GitHub_pro\AI-Vtuber\Miniconda3\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "e:\GitHub_pro\AI-Vtuber\Miniconda3\lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "e:\GitHub_pro\AI-Vtuber\Miniconda3\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
```

### 原因分析（如果可以） | Cause analysis (if possible)
网络问题（魔法没开 或 魔法不稳定）

### 问题重现步骤 | Steps to reproduce the problem
魔法不稳定的情况下

**Comment by Ikaros-521** [comment]
问题起因：魔法不稳定，或 没开魔法
解决方案：更换魔法 / 切换节点

**Comment by GOOD-N-LCM** [comment]
你使用了哪个版本？ | Which version did you use?
main

您使用的pyhon版本&系统环境？ | Your usage python version & system?
python3.10.16 & ubuntu22.04

预期行为 | Expected behavior
聊天页，谷歌识别情况下，正常语音对话

实际行为 | Actual behavior
2024-12-13 16:13:41.107 | ERROR    | __main__:do_listen_and_comment:828 - Traceback (most recent call last):
  File "/media/root1/447CBE2B3814F3372/lcm/vtube/AI-Vtuber-20241114/main.py", line 805, in do_listen_and_comment
    with sr.Microphone() as source:
  File "/home/root1/anaconda3/envs/aiv/lib/python3.10/site-packages/speech_recognition/__init__.py", line 82, in __init__
    device_info = audio.get_device_info_by_index(device_index) if device_index is not None else audio.get_default_input_device_info()
  File "/home/root1/anaconda3/envs/aiv/lib/python3.10/site-packages/pyaudio/__init__.py", line 812, in get_default_input_device_info
    device_index = pa.get_default_input_device()
OSError: No Default Input Device Available

原因分析（如果可以） | Cause analysis (if possible)
未知


问题重现步骤 | Steps to reproduce the problem
选择好配置信息，点击“一键运行”， 点击“聊天”， 点击键盘“Q”即出现上述报错。

**Comment by Ikaros-521** [comment]
> 你使用了哪个版本？ | Which version did you use? main
> 
> 您使用的pyhon版本&系统环境？ | Your usage python version & system? python3.10.16 & ubuntu22.04
> 
> 预期行为 | Expected behavior 聊天页，谷歌识别情况下，正常语音对话
> 
> 实际行为 | Actual behavior 2024-12-13 16:13:41.107 | ERROR | **main**:do_listen_and_comment:828 - Traceback (most recent call last): File "/media/root1/447CBE2B3814F3372/lcm/vtube/AI-Vtuber-20241114/main.py", line 805, in do_listen_and_comment with sr.Microphone() as source: File "/home/root1/anaconda3/envs/aiv/lib/python3.10/site-packages/speech_recognition/**init**.py", line 82, in **init** device_info = audio.get_device_info_by_index(device_index) if device_index is not None else audio.get_default_input_device_info() File "/home/root1/anaconda3/envs/aiv/lib/python3.10/site-packages/pyaudio/**init**.py", line 812, in get_default_input_device_info device_index = pa.get_default_input_device() OSError: No Default Input Device Available
> 
> 原因分析（如果可以） | Cause analysis (if possible) 未知
> 
> 问题重现步骤 | Steps to reproduce the problem 选择好配置信息，点击“一键运行”， 点击“聊天”， 点击键盘“Q”即出现上述报错。

国内网访问不了，要翻
