### ISSUE TITLE
🐛 ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by Ikaros-521** [Ikaros-521/AI-Vtuber#654]
#### 您使用的版本？ | Your usage version?
main

#### 您使用的python版本&系统环境？ | Your usage python version & system?
python：3.10.11
系统：Linux

#### 您遇到了什么问题？ | What are your problems?
```
(aivtb) ikaros@Ikaros-PC:/mnt/f/wsl_pro/AI-Vtuber$ pip install -r requirements.txt
Collecting git+https://gitee.com/ikaros-521/WenxinWorkshop-Python-SDK (from -r requirements.txt (line 2))
  Cloning https://gitee.com/ikaros-521/WenxinWorkshop-Python-SDK to /tmp/pip-req-build-k21hbg74
  Running command git clone --filter=blob:none --quiet https://gitee.com/ikaros-521/WenxinWorkshop-Python-SDK /tmp/pip-req-build-k21hbg74
  Resolved https://gitee.com/ikaros-521/WenxinWorkshop-Python-SDK to commit 2f88fb1a837c10abc5f87e4c283001c51dff8543
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-k21hbg74/setup.py", line 2, in <module>
          from wenxinworkshop import __version__
        File "/tmp/pip-req-build-k21hbg74/wenxinworkshop/__init__.py", line 12, in <module>
          from .apis import get_access_token
        File "/tmp/pip-req-build-k21hbg74/wenxinworkshop/apis.py", line 2, in <module>
          import requests
      ModuleNotFoundError: No module named 'requests'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by Ikaros-521** [comment]
先安装 requests
`pip install requests`

**Comment by watchpoints** [comment]
还是报错

**Comment by Ikaros-521** [comment]
> python -m pip install  requests
> 

还是不行多半是装错环境了
