### ISSUE TITLE
🐛 Edge-TTS无法使用，ERROR: cannot schedule new futures after interpreter shutdown

### ISSUE THREAD

**Issue by Ikaros-521** [Ikaros-521/AI-Vtuber#671]
#### 您使用的版本？ | Your usage version?
main

#### 您使用的python版本&系统环境？ | Your usage python version & system?
python：3.10.11
系统：win11

#### 您遇到了什么问题？ | What are your problems?
```
2024-02-29 23:05:05 - E:\GitHub_pro\AI-Vtuber-20240224\utils\audio_handle\my_tts.py[line:233] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_pro\AI-Vtuber-20240224\utils\audio_handle\my_tts.py", line 229, in edge_tts_api
    await communicate.save(voice_tmp_path)
  File "E:\GitHub_pro\AI-Vtuber-20240224\Miniconda3\lib\site-packages\edge_tts\communicate.py", line 458, in save
    async for message in self.stream():
  File "E:\GitHub_pro\AI-Vtuber-20240224\Miniconda3\lib\site-packages\edge_tts\communicate.py", line 305, in stream
    async with aiohttp.ClientSession(
  File "E:\GitHub_pro\AI-Vtuber-20240224\Miniconda3\lib\site-packages\aiohttp\client.py", line 1167, in __aenter__
    self._resp = await self._coro
  File "E:\GitHub_pro\AI-Vtuber-20240224\Miniconda3\lib\site-packages\aiohttp\client.py", line 805, in _ws_connect
    resp = await self.request(
  File "E:\GitHub_pro\AI-Vtuber-20240224\Miniconda3\lib\site-packages\aiohttp\client.py", line 562, in _request
    conn = await self._connector.connect(
  File "E:\GitHub_pro\AI-Vtuber-20240224\Miniconda3\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "E:\GitHub_pro\AI-Vtuber-20240224\Miniconda3\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "E:\GitHub_pro\AI-Vtuber-20240224\Miniconda3\lib\site-packages\aiohttp\connector.py", line 1155, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "E:\GitHub_pro\AI-Vtuber-20240224\Miniconda3\lib\site-packages\aiohttp\connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "E:\GitHub_pro\AI-Vtuber-20240224\Miniconda3\lib\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "E:\GitHub_pro\AI-Vtuber-20240224\Miniconda3\lib\asyncio\base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "E:\GitHub_pro\AI-Vtuber-20240224\Miniconda3\lib\asyncio\base_events.py", line 821, in run_in_executor
    executor.submit(func, *args), loop=self)
  File "E:\GitHub_pro\AI-Vtuber-20240224\Miniconda3\lib\concurrent\futures\thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown

2024-02-29 23:05:05 - E:\GitHub_pro\AI-Vtuber-20240224\utils\audio_handle\my_tts.py[line:234] - ERROR: cannot schedule new futures after interpreter shutdown
2024-02-29 23:05:05 - E:\GitHub_pro\AI-Vtuber-20240224\utils\audio.py[line:842] - ERROR: edge-tts合成失败，请排查配置、 网络等问题
```

**Comment by Ikaros-521** [comment]
https://github.com/Ikaros-521/AI-Vtuber/pull/672
