### ISSUE TITLE
🐛 GPT-SOVITS 报错 : "text_lang": dict_language[text_lang]

### ISSUE THREAD

**Issue by Ikaros-521** [Ikaros-521/AI-Vtuber#743]
#### 您使用的版本？ | Your usage version?
main

#### 您使用的python版本&系统环境？ | Your usage python version & system?
python：3.10.11
系统：win11

#### 您遇到了什么问题？ | What are your problems?
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "E:\GPT-SoVITS-0322-liuyue\GPT-SoVITS-0310-liuyue\runtime\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GPT-SoVITS-0322-liuyue\GPT-SoVITS-0310-liuyue\runtime\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GPT-SoVITS-0322-liuyue\GPT-SoVITS-0310-liuyue\runtime\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "E:\GPT-SoVITS-0322-liuyue\GPT-SoVITS-0310-liuyue\runtime\Lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "E:\GPT-SoVITS-0322-liuyue\GPT-SoVITS-0310-liuyue\runtime\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "E:\GPT-SoVITS-0322-liuyue\GPT-SoVITS-0310-liuyue\runtime\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "E:\GPT-SoVITS-0322-liuyue\GPT-SoVITS-0310-liuyue\runtime\Lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "E:\GPT-SoVITS-0322-liuyue\GPT-SoVITS-0310-liuyue\runtime\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "E:\GPT-SoVITS-0322-liuyue\GPT-SoVITS-0310-liuyue\runtime\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "E:\GPT-SoVITS-0322-liuyue\GPT-SoVITS-0310-liuyue\runtime\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "E:\GPT-SoVITS-0322-liuyue\GPT-SoVITS-0310-liuyue\runtime\Lib\site-packages\starlette\routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "E:\GPT-SoVITS-0322-liuyue\GPT-SoVITS-0310-liuyue\runtime\Lib\site-packages\starlette\routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "E:\GPT-SoVITS-0322-liuyue\GPT-SoVITS-0310-liuyue\runtime\Lib\site-packages\starlette\routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "E:\GPT-SoVITS-0322-liuyue\GPT-SoVITS-0310-liuyue\runtime\Lib\site-packages\starlette\routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "E:\GPT-SoVITS-0322-liuyue\GPT-SoVITS-0310-liuyue\runtime\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "E:\GPT-SoVITS-0322-liuyue\GPT-SoVITS-0310-liuyue\runtime\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "E:\GPT-SoVITS-0322-liuyue\GPT-SoVITS-0310-liuyue\runtime\Lib\site-packages\starlette\routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "E:\GPT-SoVITS-0322-liuyue\GPT-SoVITS-0310-liuyue\runtime\Lib\site-packages\fastapi\routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GPT-SoVITS-0322-liuyue\GPT-SoVITS-0310-liuyue\runtime\Lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GPT-SoVITS-0322-liuyue\GPT-SoVITS-0310-liuyue\api.py", line 505, in tts_endpoint
    return handle_new(
           ^^^^^^^^^^^
  File "E:\GPT-SoVITS-0322-liuyue\GPT-SoVITS-0310-liuyue\api.py", line 474, in handle_new
    sampling_rate, audio_data = next(gen)
                                ^^^^^^^^^
  File "E:\GPT-SoVITS-0322-liuyue\GPT-SoVITS-0310-liuyue\GPT_SoVITS\inference_webui.py", line 133, in inference
    "text_lang": dict_language[text_lang],
                 ~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: None
```

**Comment by Ikaros-521** [comment]
刘悦佬新版本的整合包 对接口做了大改 没法兼容。

**Comment by Ikaros-521** [comment]
https://github.com/Ikaros-521/AI-Vtuber/pull/747
