### ISSUE TITLE
Failed to establish a new connection: [WinError 10061] 無法連線，因為目標電腦拒絕連線。

### ISSUE THREAD

**Issue by albertyu123456789** [Ikaros-521/AI-Vtuber#796]
您使用的python版本&系统环境？ | Your usage python version & system?
python：3.10.11
系统：win11
您做了什么操作？ | What did you do?
一鍵運行後到聊天區塊的聊天框裡輸入文字後按發送
您遇到了什么问题？ | What are your problems?

2024-05-01 20:48:19 - D:\AI-Vtuber\webui.py[line:261] - INFO: 运行程序: main
2024-05-01 20:48:19 - D:\AI-Vtuber\webui.py[line:336] - INFO: 程序开始运行
2024-05-01 20:48:26 - D:\AI-Vtuber\utils\common.py[line:1035] - ERROR: Traceback (most recent call last):
  File "D:\AI-Vtuber\Miniconda3\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "D:\AI-Vtuber\Miniconda3\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "D:\AI-Vtuber\Miniconda3\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 無法連線，因為目標電腦拒絕連線。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AI-Vtuber\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "D:\AI-Vtuber\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "D:\AI-Vtuber\Miniconda3\lib\site-packages\urllib3\connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "D:\AI-Vtuber\Miniconda3\lib\http\client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\AI-Vtuber\Miniconda3\lib\http\client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\AI-Vtuber\Miniconda3\lib\http\client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\AI-Vtuber\Miniconda3\lib\http\client.py", line 1038, in _send_output
    self.send(msg)
  File "D:\AI-Vtuber\Miniconda3\lib\http\client.py", line 976, in send
    self.connect()
  File "D:\AI-Vtuber\Miniconda3\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "D:\AI-Vtuber\Miniconda3\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001E66197A5C0>: Failed to establish a new connection: [WinError 10061] 無法連線，因為目標電腦拒絕連線。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AI-Vtuber\Miniconda3\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\AI-Vtuber\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "D:\AI-Vtuber\Miniconda3\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8082): Max retries exceeded with url: /send (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E66197A5C0>: Failed to establish a new connection: [WinError 10061] 無法連線，因為目標電腦拒絕連線。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AI-Vtuber\utils\common.py", line 1017, in send_request
    response = requests.post(url, headers=headers, data=json.dumps(json_data), timeout=timeout)
  File "D:\AI-Vtuber\Miniconda3\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "D:\AI-Vtuber\Miniconda3\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\AI-Vtuber\Miniconda3\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\AI-Vtuber\Miniconda3\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\AI-Vtuber\Miniconda3\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8082): Max retries exceeded with url: /send (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E66197A5C0>: Failed to establish a new connection: [WinError 10061] 無法連線，因為目標電腦拒絕連線。'))

2024-05-01 20:48:26 - D:\AI-Vtuber\utils\common.py[line:1036] - ERROR: 请求出错: HTTPConnectionPool(host='127.0.0.1', port=8082): Max retries exceeded with url: /send (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E66197A5C0>: Failed to establish a new connection: [WinError 10061] 無法連線，因為目標電腦拒絕連線。'))

**Comment by Ikaros-521** [comment]
![image](https://github.com/Ikaros-521/AI-Vtuber/assets/40910637/b6c38509-d7ce-4ca2-afeb-2aaccd287443)
![image](https://github.com/Ikaros-521/AI-Vtuber/assets/40910637/5a67a7e3-fcb9-4eef-80b3-b394407b6b6b)
只有到http 服务启动后，才能接受api的调用，其实就是你的聊天消息发送太快了，程序还没完全启动，所以没法响应
