### ISSUE TITLE
🐛 AttributeError: 'DanmakuMessage' object has no attribute 'face'

### ISSUE THREAD

**Issue by gold74386** [Ikaros-521/AI-Vtuber#805]
#### 您使用的版本？ | Your usage version?
例如：main 或者 20230806

#### 您使用的python版本&系统环境？ | Your usage python version & system?
例如：
python：3.10.11
系统：win11

#### 您期望的结果是怎样的？ | What is your expected outcome?
Traceback (most recent call last):
  File "C:\Users\gold\miniconda3\envs\vtu\lib\site-packages\blivedm\clients\ws_base.py", line 492, in _handle_command
    self._handler.handle(self, command)
  File "C:\Users\gold\miniconda3\envs\vtu\lib\site-packages\blivedm\handlers.py", line 129, in handle
    callback(self, client, command)
  File "C:\Users\gold\miniconda3\envs\vtu\lib\site-packages\blivedm\handlers.py", line 70, in __danmu_msg_callback
    return self._on_danmaku(client, web_models.DanmakuMessage.from_command(command['info']))
  File "C:\Users\gold\Desktop\AI-Vtuber\main.py", line 1492, in _on_danmaku
    user_face = message.face
AttributeError: 'DanmakuMessage' object has no attribute 'face'

**Comment by gold74386** [comment]
Traceback (most recent call last):
  File "C:\Users\gold\miniconda3\envs\vtu\lib\site-packages\blivedm\clients\ws_base.py", line 492, in _handle_command
    self._handler.handle(self, command)
  File "C:\Users\gold\miniconda3\envs\vtu\lib\site-packages\blivedm\handlers.py", line 129, in handle
    callback(self, client, command)
  File "C:\Users\gold\miniconda3\envs\vtu\lib\site-packages\blivedm\handlers.py", line 70, in __danmu_msg_callback
    return self._on_danmaku(client, web_models.DanmakuMessage.from_command(command['info']))
  File "C:\Users\gold\Desktop\AI-Vtuber\main.py", line 1492, in _on_danmaku
    user_face = message.face
AttributeError: 'DanmakuMessage' object has no attribute 'face'

**Comment by Ikaros-521** [comment]
blivedm库是否是官方最新版本，如果是从pypi装的，就是旧版，没有face属性，如果库版本正常，那就把face删了吧

**Comment by Ikaros-521** [comment]
或者 修改为
user_face = message.face if hasattr(message, 'face') else None

**Comment by Ikaros-521** [comment]
fixed #806
