### ISSUE TITLE
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

### ISSUE THREAD

**Issue by albertyu123456789** [Ikaros-521/AI-Vtuber#857]
### 操作系统

Windows

### Python 版本

3.10.11

### AI Vtuber 版本

20240524

### 描述问题

pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

### 复现步骤

1.開啟"1.双击我启动程序"
2.報錯

### 截图或日志

pygame 2.5.2 (SDL 2.28.3, Python 3.10.14)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "D:\AI-Vtuber\webui.py", line 13, in <module>
    from utils.audio import Audio
  File "D:\AI-Vtuber\utils\audio.py", line 16, in <module>
    from elevenlabs import generate, play, set_api_key
  File "D:\AI-Vtuber\Miniconda3\lib\site-packages\elevenlabs\__init__.py", line 1, in <module>
    from .api import *  # noqa F403
  File "D:\AI-Vtuber\Miniconda3\lib\site-packages\elevenlabs\api\__init__.py", line 2, in <module>
    from .history import *  # noqa F403
  File "D:\AI-Vtuber\Miniconda3\lib\site-packages\elevenlabs\api\history.py", line 9, in <module>
    from .voice import VoiceSettings
  File "D:\AI-Vtuber\Miniconda3\lib\site-packages\elevenlabs\api\voice.py", line 21, in <module>
    class VoiceClone(API):
  File "D:\AI-Vtuber\Miniconda3\lib\site-packages\elevenlabs\api\voice.py", line 29, in VoiceClone
    def computed_files_tuple(cls, values) -> List[str]:
  File "D:\AI-Vtuber\Miniconda3\lib\site-packages\pydantic\deprecated\class_validators.py", line 243, in root_validator
    return root_validator()(*__args)  # type: ignore
  File "D:\AI-Vtuber\Miniconda3\lib\site-packages\pydantic\deprecated\class_validators.py", line 249, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.7/u/root-validator-pre-skip

**Comment by 0x648** [comment]
请正确描述问题
