### ISSUE TITLE
🐛 Bug: 出现异常

### ISSUE THREAD

**Issue by qingxiao-jie** [Ikaros-521/AI-Vtuber#920]
### 操作系统

Windows

### Python 版本

3.11.0

### AI Vtuber 版本

202407

### 描述问题

2024-07-12 16:20:03.250 | DEBUG    | utils.my_log:<module>:57 - 配置文件路径=config.json
pygame 2.6.0 (SDL 2.28.4, Python 3.11.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
F:\AI-Vtuber\.venv\Lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
2024-07-12 16:20:03.819 | INFO     | utils.audio:__init__:79 - 文案模式的Audio初始化...
2024-07-12 16:20:03.990 | INFO     | __main__:goto_func_page:5448 - 本地Live2D模型名列表：['Haru', 'hibiki', 'Hiyori']
2024-07-12 16:20:04.148 | INFO     | __main__:goto_func_page:5646 - 声卡输入设备=[{'device_index': 0, 'device_info': 'Microsoft Sound Mapper - Input'}, {'device_index': 1, 'device_info': '麦克风 (2- Realtek High Definition'}, {'
device_index': 2, 'device_info': 'VoiceMeeter Output (VB-Audio Vo'}, {'device_index': 7, 'device_info': '主声音捕获驱动程序'}, {'device_index': 8, 'device_info': '麦克风 (2- Realtek High Definition Audio)'}, {'device_index': 9, 
'device_info': 'VoiceMeeter Output (VB-Audio VoiceMeeter VAIO)'}, {'device_index': 17, 'device_info': '麦克风 (2- Realtek High Definition Audio)'}, {'device_index': 18, 'device_info': 'VoiceMeeter Output (VB-Audio VoiceMeeter VA
IO)'}, {'device_index': 20, 'device_info': '麦克风 (Realtek HD Audio Mic input)'}, {'device_index': 22, 'device_info': '绾胯矾杈撳叆 (Realtek HD Audio Line input)'}, {'device_index': 23, 'device_info': '立体声混音 (Realtek HD Au
dio Stereo input)'}, {'device_index': 24, 'device_info': 'VoiceMeeter Output (VoiceMeeter vaio)'}]
2024-07-12 16:20:04.210 | WARNING  | utils.data_analysis:get_comment_word_cloud_option:81 - 数据库：data/data.db 不存在，如果您是第一次启动项目，且没有 运行的情况下，那么请忽略此报错信息，正常运行后，会自动创建数据库，无须担心
Traceback (most recent call last):
  File "F:\AI-Vtuber\webui.py", line 6560, in <module>
    goto_func_page()
  File "F:\AI-Vtuber\webui.py", line 6244, in goto_func_page
    echart_comment_word_cloud = ui.echart(data_analysis.get_comment_word_cloud_option(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI-Vtuber\.venv\Lib\site-packages\nicegui\elements\echart.py", line 36, in __init__
    for key in options:
TypeError: 'NoneType' object is not iterable

### 复现步骤

1.首先运行webui.py遇到bug:pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.     
2.然后降低pydantic版本为1.10.7
3.接着重新运行webui.py

**Comment by qiuzi** [comment]
老哥最终解决了吗？

**Comment by qingxiao-jie** [comment]
> 老哥最终解决了吗？

没有解决，找到最后是创建表那里问题，创建不了新的数据表

**Comment by GOOD-N-LCM** [comment]
怎么样了老哥。  我也是卡在了这里。最开始我以为是requests版本的问题。升级完requests之后一回事这个错误。

**Comment by GOOD-N-LCM** [comment]
怎么样，老哥 。   请您解决解决了么？

**Comment by hyuuuliu** [comment]
Same problem. Has it been fixed already?

**Comment by xiaomaofei** [comment]
Same problem.

**Comment by GOOD-N-LCM** [comment]
最后去下载整合包使用即可...
