### ISSUE TITLE
🐛 Bug: Task exception was never retrieved  TypeError: unhashable type: 'dict'

### ISSUE THREAD

**Issue by Ikaros-521** [Ikaros-521/AI-Vtuber#938]
### 操作系统

Windows

### Python 版本

3.10.11

### AI Vtuber 版本

20240725

### 描述问题

```
Task exception was never retrieved
future: <Task finished name='Task-135' coro=<AsyncServer._handle_event_internal() done, defined at E:\GitHub_pro\AI-Vtuber-20240702\Miniconda3\lib\site-packages\socketio\async_server.py:595> exception=TypeError("unhashable type: 'dict'")>
Traceback (most recent call last):
  File "E:\GitHub_pro\AI-Vtuber-20240702\Miniconda3\lib\site-packages\socketio\async_server.py", line 597, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "E:\GitHub_pro\AI-Vtuber-20240702\Miniconda3\lib\site-packages\socketio\async_server.py", line 631, in _trigger_event
    ret = await handler(*args)
  File "E:\GitHub_pro\AI-Vtuber-20240702\Miniconda3\lib\site-packages\nicegui\nicegui.py", line 136, in _on_handshake
    client = Client.instances.get(client_id)
TypeError: unhashable type: 'dict'
```

### 复现步骤

整合包直接运行报错

**Comment by Ikaros-521** [comment]
重装整个环境
