### ISSUE TITLE
🐛 Bug: future: <Task finished name='Task-141' coro=<AsyncServer._handle_event_internal() done client = Client.instances.get(client_id) TypeError: unhashable type: 'dict'

### ISSUE THREAD

**Issue by Ikaros-521** [Ikaros-521/AI-Vtuber#942]
### 操作系统

Windows

### Python 版本

3.10.11

### AI Vtuber 版本

20240726

### 描述问题

```
Task exception was never retrieved
future: <Task finished name='Task-141' coro=<AsyncServer._handle_event_internal() done, defined at e:\GitHub_pro\AI-Vtuber\Miniconda3\lib\site-packages\socketio\async_server.py:595> exception=TypeError("unhashable type: 'dict'")>
Traceback (most recent call last):
  File "e:\GitHub_pro\AI-Vtuber\Miniconda3\lib\site-packages\socketio\async_server.py", line 597, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "e:\GitHub_pro\AI-Vtuber\Miniconda3\lib\site-packages\socketio\async_server.py", line 631, in _trigger_event
    ret = await handler(*args)
  File "e:\GitHub_pro\AI-Vtuber\Miniconda3\lib\site-packages\nicegui\nicegui.py", line 136, in _on_handshake
    client = Client.instances.get(client_id)
TypeError: unhashable type: 'dict'
```

### 复现步骤

0725整合包报错

**Comment by Ikaros-521** [comment]
python环境问题导致

**Comment by Ikaros-521** [comment]
https://github.com/Ikaros-521/AI-Vtuber/pull/944
