### ISSUE TITLE
🙋 问题交流：File "/opt/conda/envs/AI-Vtuber/lib/python3.10/site-packages/nicegui/elements/echart.py", line 36, in init for key in options: TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by zhaowang0326** [Ikaros-521/AI-Vtuber#967]
### 操作系统

Linux

### Python 版本

3.10.11

### AI Vtuber 版本

20240501

### 描述问题

2024-08-12 16:53:26.577 | INFO     | __main__:goto_func_page:5696 - 声卡输入设备=[]
2024-08-12 16:53:26.670 | WARNING  | utils.data_analysis:get_comment_word_cloud_option:81 - 数据库：data/data.db 不存在，如果您是第一次启动项目，且没有 运行的情况下，那么请忽略此报错信息，正常运行后，会自动创建数据库，无须担心
Traceback (most recent call last):
  File "/home/jovyan/zhaowang/project/AI-Vtuber/webui.py", line 6643, in <module>
    goto_func_page()
  File "/home/jovyan/zhaowang/project/AI-Vtuber/webui.py", line 6329, in goto_func_page
    echart_comment_word_cloud = ui.echart(data_analysis.get_comment_word_cloud_option(
  File "/opt/conda/envs/AI-Vtuber/lib/python3.10/site-packages/nicegui/elements/echart.py", line 36, in __init__
    for key in options:
TypeError: 'NoneType' object is not iterable

### 复现步骤

python webui.py 启动失败：TypeError: 'NoneType' object is not iterable

### 期望的结果

up主给出解决方案：nicegui改为1.4.10，原nicegui版本为1.4.30，修改版本后启动成功

**Comment by Ikaros-521** [comment]
不同操作系统下 库版本可能并不完全适配，后期考虑针对Linux单独出一个版本依赖。
