### ISSUE TITLE
🐛 Bug: OSError: [WinError 126] 找不到指定的模块。 Error loading "D:\DH_live-20240802\DH_live\Miniconda3\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

### ISSUE THREAD

**Issue by Ikaros-521** [Ikaros-521/AI-Vtuber#975]
### 操作系统

Windows

### Python 版本

3.10.11

### AI Vtuber 版本

main

### 描述问题

```
Traceback (most recent call last):
  File "D:\DH_live-20240802\DH_live\demo_avatar.py", line 7, in <module>
    from talkingface.audio_model import AudioModel
  File "D:\DH_live-20240802\DH_live\talkingface\audio_model.py", line 5, in <module>
    import torch
  File "D:\DH_live-20240802\DH_live\Miniconda3\lib\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] 找不到指定的模块。 Error loading "D:\DH_live-20240802\DH_live\Miniconda3\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.
```

### 复现步骤

整合包直接运行

**Comment by Ikaros-521** [comment]
安装Visual Studio，把C++桌面开发装好
https://visualstudio.microsoft.com/zh-hans/vs/community/

**Comment by JerryDaHeLian** [comment]
仍然不好使！

**Comment by Ikaros-521** [comment]
> 仍然不好使！

要么没装对 要么重装torch 还不行那没救了
